# Generated by Django 4.2.4 on 2023-08-30 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Midjouney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zapros', models.CharField(max_length=255, verbose_name='Запрос')),
                ('otvet', models.ImageField(upload_to='midjouney', verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Midjouney',
                'verbose_name_plural': 'Midjouneys',
            },
        ),
        migrations.CreateModel(
            name='Parametr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zapros', models.CharField(max_length=255, verbose_name='Запрос')),
            ],
            options={
                'verbose_name': 'Parametr',
                'verbose_name_plural': 'Parametrs',
            },
        ),
        migrations.CreateModel(
            name='Struktura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zapros', models.CharField(max_length=255, verbose_name='Запрос')),
                ('otvet', models.ImageField(upload_to='struktura', verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Struktura',
                'verbose_name_plural': 'Strukturas',
            },
        ),
        migrations.CreateModel(
            name='ImageParametr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('otvet', models.ImageField(upload_to='parametr', verbose_name='Ответ')),
                ('parametr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='midjouney.parametr', verbose_name='Параметр')),
            ],
            options={
                'verbose_name': 'ImageParametr',
                'verbose_name_plural': 'ImageParametrs',
            },
        ),
    ]
