# Generated by Django 4.2.4 on 2023-08-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_banner', models.ImageField(upload_to='advertisement', verbose_name='Изображение баннера')),
                ('link_banner', models.URLField(verbose_name='Ссылка')),
                ('image_card', models.ImageField(upload_to='advertisement', verbose_name='Изображение карточки')),
                ('link_card', models.URLField(verbose_name='Ссылка')),
                ('image_card_detail', models.ImageField(upload_to='advertisement', verbose_name='Изображение карточки детально')),
                ('link_card_detail', models.URLField(verbose_name='Ссылка')),
                ('promt_image', models.ImageField(upload_to='advertisement', verbose_name='Изображение промта')),
                ('promt_link', models.URLField(verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Тег рекламы',
                'verbose_name_plural': 'Теги рекламы',
            },
        ),
    ]
