# Generated by Django 4.2.4 on 2023-08-22 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_advertisementtag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisementtag',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='advertisementtag',
            name='updated_at',
        ),
    ]
