# Generated by Django 4.2.4 on 2023-08-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_remove_advertisementtag_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisementtag',
            name='image_banner',
            field=models.ImageField(blank=True, upload_to='advertisement', verbose_name='Изображение баннера'),
        ),
        migrations.AlterField(
            model_name='advertisementtag',
            name='image_card',
            field=models.ImageField(blank=True, upload_to='advertisement', verbose_name='Изображение карточки'),
        ),
        migrations.AlterField(
            model_name='advertisementtag',
            name='image_card_detail',
            field=models.ImageField(blank=True, upload_to='advertisement', verbose_name='Изображение карточки детально'),
        ),
        migrations.AlterField(
            model_name='advertisementtag',
            name='link_banner',
            field=models.URLField(blank=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='advertisementtag',
            name='link_card',
            field=models.URLField(blank=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='advertisementtag',
            name='promt_image',
            field=models.ImageField(blank=True, upload_to='advertisement', verbose_name='Изображение промта'),
        ),
        migrations.AlterField(
            model_name='advertisementtag',
            name='promt_link',
            field=models.URLField(blank=True, verbose_name='Ссылка'),
        ),
    ]
