# Generated by Django 4.2.4 on 2023-08-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0004_alter_advertisementtag_image_banner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisementtag',
            name='link_card_detail',
            field=models.URLField(blank=True, verbose_name='Ссылка'),
        ),
    ]
