# Generated by Django 4.2.4 on 2023-08-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NeuralNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='neuralnetwork', verbose_name='Изображение')),
                ('status', models.CharField(choices=[('free', 'Бесплатно'), ('paid', 'Платно')], max_length=255, verbose_name='Статус платности')),
                ('icon_18', models.BooleanField(default=False, verbose_name='Иконка 18+')),
                ('icon_ru', models.BooleanField(default=False, verbose_name='Иконка русский язык')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Нейронная сеть',
                'verbose_name_plural': 'Нейронные сети',
            },
        ),
    ]
