# Generated by Django 4.2.4 on 2023-08-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neauralnetwork', '0002_alter_neuralnetwork_options_neuralnetwork_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='DOSTUP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Доступ(платно/Бесплатно/Триал)',
                'verbose_name_plural': 'Доступ(платно/Бесплатно/Триал)',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Сфера применения',
                'verbose_name_plural': 'Сферы применения',
            },
        ),
        migrations.RemoveField(
            model_name='neuralnetwork',
            name='status',
        ),
        migrations.AddField(
            model_name='neuralnetwork',
            name='link',
            field=models.URLField(default=1, verbose_name='Ссылка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='neuralnetwork',
            name='zadacha',
            field=models.CharField(default=1, max_length=255, verbose_name='Задача'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='neuralnetwork',
            name='dostup',
            field=models.ManyToManyField(to='neauralnetwork.dostup', verbose_name='Доступ(платно/Бесплатно/Триал)'),
        ),
        migrations.AddField(
            model_name='neuralnetwork',
            name='tag',
            field=models.ManyToManyField(to='neauralnetwork.tag', verbose_name='Сфера применения'),
        ),
    ]
