# Generated by Django 4.2.4 on 2023-08-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neauralnetwork', '0003_dostup_tag_remove_neuralnetwork_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dostup',
            options={'verbose_name': 'Доступ', 'verbose_name_plural': 'Доступ'},
        ),
        migrations.AlterField(
            model_name='dostup',
            name='title',
            field=models.CharField(choices=[('Платно', 'Платно'), ('Бесплатно', 'Бесплатно'), ('Триал', 'Триал')], default='Платно', max_length=255, verbose_name='Доступ'),
        ),
    ]
